server:
  port: 8082

spring:
  application:
    name: perf-poc-consistent-hash

shard:
  virtual-nodes-per-node: 150
  nodes:
    - name: redis-1
      host: localhost
      port: 6379
    - name: redis-2
      host: localhost
      port: 6380
    - name: redis-3
      host: localhost
      port: 6381

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
