server:
  port: 8084

spring:
  application:
    name: refund-flow-poc
  datasource:
    url: jdbc:h2:mem:refunds;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
