server:
  port: 8085

spring:
  application:
    name: multi-currency-poc
  datasource:
    url: jdbc:h2:mem:fx;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
